# -*- coding: utf-8 -*-
"""Kideny info_chatbot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xXfOPcasDLo24wvkPUlc_beQMUWAyZcd

#**This is kideny disease chatbot**
"""

pip install nltk

pip install newspaper3k

#import library
from newspaper import Article
import random
import string
import nltk
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np
import warnings
warnings.filterwarnings('ignore')

#dowload the punnkt package
nltk.download ('punkt', quiet = True)

"""**I am use in the arcticle the data from website for kidney-disease https://www.healthline.com/health/kidney-disease
please check it. 
Any data from google web we can creat chatbot for give proper knowdlge'**
"""

article = Article("https://www.healthline.com/health/kidney-disease")
article.download()
article.parse()
article.nlp()
corpus= article.text

print(corpus)

text = corpus
sentencne_list = nltk.sent_tokenize(text)

print (sentencne_list)

def greet_response(text):
  text = text.lower()
  #Bots response
  bot_greet= ["how","hello", "hey","hi","hola"]
  #user respnse
  user_greet= ["hi","hello", "great","waw","wassup"]

  for word in text.split():
   if word in user_greet:
    return random.choice(bot_greet)

def index_sort(list_var):
  length = len(list_var)
  list_index = list(range(0, length))

  x = list_var
  for i in range(length):
    for j in range(length):
      if x[list_index[i]] > [list_index[j]]:
        
        temp =list_index[i]
        list_index[i]= list_index[j]
        list_index[j]= temp

  return list_index

#creat chot bot
def bot_resp(user_input):
  user_input= user_input.lower()
  sentencne_list.append(user_input)
  bot_resp = ''
  cm = CountVectorizer().fit_transform(sentencne_list)
  similarity_scr =cosine_similarity(cm[-1],cm)
  similarity_scr_list = similarity_scr.flatten()
  index = index_sort(similarity_scr_list)
  index = index[1:]
  res_flag = 0

  j = 0 
  for i in range(len(index)):
    if similarity_scr_list[index[i]] > 0.0:
      bot_resp = bot_resp+' '+sentencne_list[index[i]]
      res_flag = 1
      j = j+1
    if j > 2:
      break

  if res_flag == 0:
    bot_resp = bot_resp+' '+ "I apologize, I don't understant."


  sentencne_list.remove(user_input)

  return bot_resp

# start chat
print("Dr.bot: I am a doctor bot ,I will give answer about chromic kideny  disease ")

exit_list = ['exit','see you','bye', 'quit','break']

while(True):
  user_input = input()
  if user_input.lower() in exit_list:
    print('Dr.bot: Chat with you later Have a nice day!')
    break
  else:
    if greet_response(user_input) != None:
      print('Dr.bot: '+greet_response(user_input))
    else:
      print('Dr.bot: '+bot_resp(user_input))